live_config_reload = true

import = [
  "~/dotfiles/.config/alacritty/themes/themes/tokyo-night.toml",
]

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/opt/homebrew/bin/zsh"

[env]
TERM = "xterm-256color"

[window]
blur = true
decorations = "Buttonless"
opacity = 0.8
padding.x = 16
padding.y = 0

[font]
glyph_offset.x = 0
glyph_offset.y = 0
size = 14

[font.normal]
family = "SFMono Nerd Font"
style = "Regular"

[font.bold]
family = "SFMono Nerd Font"
style = "Bold"

[font.italic]
family = "SFMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "SFMono Nerd Font"
style = "Bold Italic"

[keyboard]
bindings = [
  {key = "Enter", mods = "Command", action = "ToggleFullscreen"}, # ⌘ + enter puts window in macOS full screen
  {key = "Right", mods = "Alt", chars = "\u001BF"}, # opt + right and left jump between words
  {key = "Left", mods = "Alt", chars = "\u001BB"},
  {key = "T", mods = "Command", chars = "\u0002c"}, # ⌘ + T opens a new tmux window
  {key = "D", mods = "Command", chars = "\u0002%"}, # ⌘ + d adds a pane to the right (splits window vertically)
  {key = "D", mods = "Command|Shift", chars = "\u0002\""}, # ⌘ + ⇧ + d adds a pane below (splits window horizontally)
  {key = "W", mods = "Command", chars = "\u0002x"}, # ⌘ + w prompts you to close the pane, "y" to confirm
  {key = "Down", mods = "Command", chars = "\u0002\u001b[B"}, # ⌘ + arrows are for directional navigation around the panes. move down a pane
  {key = "Up", mods = "Command", chars = "\u0002\u001b[A"}, # move up a pane
  {key = "Left", mods = "Command", chars = "\u0002\u001b[D"}, # move left a pane
  {key = "Right", mods = "Command", chars = "\u0002\u001b[C"}, # move right a pane
  {key = "Enter", mods = "Command|Shift", chars = "\u0002z"}, # ⌘ + ⇧ + enter maximizes the pane within the alacritty window
]
